specVersion: 0.0.4
description: Fanszoid Tickets Marketplace
repository: https://github.com/Fanszoid/fanszoid-graph
features:
  - ipfsOnEthereumContracts
  - fullTextSearch
schema:
  file: ./schema.graphql
dataSources:
  # ---------------------------------------------------------
  # Tickets
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: Ticket
    network: {{network}}
    source:
      address: '{{address:ticket}}'
      abi: Ticket
      startBlock: {{startBlock:ticket}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Ticket
        - TicketBalance
        - User
        - Transfer
      abis:
        - name: Ticket
          file: ./abis/Ticket.json
      eventHandlers:
        - event: TransferSingle(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleTransferSingle
        - event: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[])
          handler: handleTransferBatch
      file: ./src/handlers/ticketsHandler.ts
  # ---------------------------------------------------------
  # MARKETPLACE 
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: Marketplace
    network: {{network}}
    source:
      address: '{{address:marketplace}}'
      abi: Marketplace
      startBlock: {{startBlock:marketplace}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Ticket
        - TicketBalance
        - User
        - Transfer
      abis:
        - name: Marketplace
          file: ./abis/Marketplace.json
      eventHandlers:
        - event: TicketPublished(indexed uint256,address,indexed uint256,uint256,uint256,uint256,uint256,bool,string)
          handler: handleTicketPublished
        - event: EventCreated(indexed uint256,address,string)
          handler: handleEventCreated
        - event: EventDeleted(indexed uint256)
          handler: handleEventDeleted
        - event: TicketDeleted(indexed uint256,address,uint256[],uint256[])
          handler: handleTicketDeleted
        - event: TicketBought(indexed uint256,address,address,uint256,uint256)
          handler: handleTicketBought
        - event: AskSetted(indexed uint256,indexed address,uint256,uint256)
          handler: handleAskSetted
        - event: AskRemoved(indexed address,indexed uint256)
          handler: handleAskRemoved
        - event: EventOwnershipTransferred(indexed uint256,address)
          handler: handleEventOwnershipTransferred
        - event: CreatorRoyaltyModifiedOnEvent(indexed uint256,uint256)
          handler: handleCreatorRoyaltyModifiedOnEvent
        - event: CreatorRoyaltyModifiedOnTicket(indexed uint256,uint256)
          handler: handleCreatorRoyaltyModifiedOnTicket
        - event: TicketEdited(indexed uint256,string)
          handler: handleTicketUriModification
        - event: EventEdited(indexed uint256,string)
          handler: handleEventUriModification
      file: ./src/handlers/marketplaceHandler.ts