specVersion: 0.0.4
description: Fanszoid Tickets Marketplace
repository: https://github.com/Fanszoid/fanszoid-graph
features:
  - ipfsOnEthereumContracts
  - fullTextSearch
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Ticket
    network: mumbai
    source:
      address: '0xd18Ce9e4ec21ED39C50BfB63d40a5c0C591e238B'
      abi: Ticket
      startBlock: 26728706
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Ticket
        - Balance
        - User
        - Transfer
      abis:
        - name: Ticket
          file: ./abis/Ticket.json
      eventHandlers:
        - event: TransferSingle(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleTransferSingle
        - event: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[])
          handler: handleTransferBatch
      file: ./src/handlers/ticketsHandler.ts
  - kind: ethereum/contract
    name: Membership
    network: mumbai
    source:
      address: '0xF94F58EBA614a78118Cba0667F22268f478c88B8'
      abi: Membership
      startBlock: 26728706
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Membership
        - Balance
        - User
        - Transfer
      abis:
        - name: Membership
          file: ./abis/Membership.json
      eventHandlers:
        - event: TransferSingle(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleTransferSingle
        - event: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[])
          handler: handleTransferBatch
      file: ./src/handlers/membershipsHandler.ts
  - kind: ethereum/contract
    name: TicketsMarketplace
    network: mumbai
    source:
      address: '0x8193dEbbeA93238aeB710442b122D6B747DB24C4'
      abi: TicketsMarketplace
      startBlock: 26728706
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Ticket
        - Balance
        - User
        - Transfer
      abis:
        - name: TicketsMarketplace
          file: ./abis/TicketsMarketplace.json
      eventHandlers:
        - event: TicketPublished(indexed uint256,address,indexed uint256,uint256,uint256,uint256,uint256,bool,string)
          handler: handleTicketPublishedLegacy
        - event: TicketPublished(indexed uint256,address,indexed uint256,uint256,(uint256,uint256,uint256,uint256,bool,string,bool,(uint256,address[])[]),string)
          handler: handleTicketPublished
        - event: TicketEdited(indexed uint256,string)
          handler: handleTicketUriModification
        - event: TicketBought(indexed uint256,address,address,uint256,uint256)
          handler: handleTicketBought
        - event: TicketDeleted(indexed uint256,address,uint256[],uint256[])
          handler: handleTicketDeletedLegacy
        - event: TicketsDeleted(uint256[],address,uint256[])
          handler: handleTicketDeleted
        - event: AskSetted(indexed uint256,indexed address,uint256,uint256)
          handler: handleAskSetted
        - event: AskRemoved(indexed address,indexed uint256)
          handler: handleAskRemoved
        - event: CreatorRoyaltyModifiedOnTicket(indexed uint256,uint256)
          handler: handleCreatorRoyaltyModifiedOnTicket
        - event: AllowanceAdded(indexed uint256,indexed uint256,(uint256,address[]))
          handler: handleAllowanceAdded
        - event: AllowanceConsumed(indexed uint256)
          handler: handleAllowanceConsumed
        - event: AllowanceRemoved(indexed uint256,indexed uint256)
          handler: handleAllowanceRemoved
      file: ./src/handlers/ticketsMarketplaceHandler.ts
  - kind: ethereum/contract
    name: MembershipsMarketplace
    network: mumbai
    source:
      address: '0xcB2C094d7C01111341d192D0c40dCE1Dbcbdd3dd'
      abi: MembershipsMarketplace
      startBlock: 26728706
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Membership
        - Balance
        - User
        - Transfer
      abis:
        - name: MembershipsMarketplace
          file: ./abis/MembershipsMarketplace.json
      eventHandlers:
        - event: MembershipPublished(address,indexed uint256,uint256,uint256,uint256,uint256,bool,string)
          handler: handleMembershipPublishedLegacy
        - event: MembershipPublished(address,indexed uint256,uint256,(uint256,uint256,uint256,uint256,bool,string,bool,(uint256,address[])[]),string)
          handler: handleMembershipPublished
        - event: MembershipEdited(indexed uint256,string)
          handler: handleMembershipUriModification
        - event: MembershipBought(indexed uint256,address,address,uint256,uint256)
          handler: handleMembershipBought
        - event: MembershipDeleted(indexed uint256,address,uint256[],uint256[])
          handler: handleMembershipDeletedLegacy
        - event: MembershipsDeleted(uint256[],address,uint256[])
          handler: handleMembershipDeleted
        - event: AskSetted(indexed uint256,indexed address,uint256,uint256)
          handler: handleAskSetted
        - event: AskRemoved(indexed address,indexed uint256)
          handler: handleAskRemoved
        - event: CreatorRoyaltyModifiedOnMembership(indexed uint256,uint256)
          handler: handleCreatorRoyaltyModifiedOnMembership
        - event: AllowanceAdded(indexed uint256,indexed uint256,(uint256,address[]))
          handler: handleAllowanceAdded
        - event: AllowanceConsumed(indexed uint256)
          handler: handleAllowanceConsumed
        - event: AllowanceRemoved(indexed uint256,indexed uint256)
          handler: handleAllowanceRemoved
      file: ./src/handlers/membershipsMarketplaceHandler.ts
  - kind: ethereum/contract
    name: Admin
    network: mumbai
    source:
      address: '0x447C4DAd5b8257d8C53Ea95e472aAc9eA98ADDaf'
      abi: Admin
      startBlock: 26728706
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Ticket
        - Balance
        - User
        - Transfer
      abis:
        - name: Admin
          file: ./abis/Admin.json
      eventHandlers:
        - event: EventCreated(indexed uint256,address,string)
          handler: handleEventCreated
        - event: EventDeleted(indexed uint256)
          handler: handleEventDeleted
        - event: EventOwnershipTransferred(indexed uint256,address)
          handler: handleEventOwnershipTransferred
        - event: CreatorRoyaltyModifiedOnEvent(indexed uint256,uint256)
          handler: handleCreatorRoyaltyModifiedOnEvent
        - event: EventEdited(indexed uint256,string)
          handler: handleEventUriModification
        - event: MembershipAssignedToTicket(indexed uint256,address,uint256[])
          handler: handleMembershipsAssigned
        - event: MembershipRemovedFromTicket(indexed uint256,address)
          handler: handleDisallowMembership
        - event: MembershipTokenIdRemovedFromTicket(indexed uint256,address,uint256)
          handler: handleDisallowMembershipTokenId
        - event: EventPaused(indexed uint256)
          handler: handleEventPaused
        - event: EventUnpaused(indexed uint256)
          handler: handleEventUnpaused
        - event: CollaboratorAdded(indexed uint256,indexed address)
          handler: handleCollaboratorAdded
        - event: CollaboratorRemoved(indexed uint256,indexed address)
          handler: handleCollaboratorRemoved

      file: ./src/handlers/adminHandler.ts