specVersion: 0.0.4
description: Fanszoid Tickets Marketplace
repository: https://github.com/Fanszoid/fanszoid-graph
schema:
  file: ./schema.graphql
dataSources:
  # ---------------------------------------------------------
  # TicketsNFT
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: TicketsNFT
    network: {{network}}
    source:
      address: '{{address:tickets}}'
      abi: TicketsNFT
      startBlock: {{startBlock:tickets}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - TicketType
        - User
      abis:
        - name: TicketsNFT
          file: ./abis/TicketsNFT.json
      eventHandlers:
        - event: ticketsPublished(uint256,uint256,uint256[],uint256[],uint256[],uint256[],string[],address)
          handler: handleTicketsPublished
        - event: TransferSingle(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleTransferSingle
        - event: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[])
          handler: handleTransferBatch
      file: ./src/handlers/ticketsHandler.ts
  # ---------------------------------------------------------
  # MARKETPLACE 
  # ---------------------------------------------------------
  - kind: ethereum/contract
    name: FanszoidMarketplace
    network: {{network}}
    source:
      address: '{{address:marketplace}}'
      abi: FanszoidMarketplace
      startBlock: {{startBlock:marketplace}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Event
        - Ticket
        - TicketType
        - User
      abis:
        - name: FanszoidMarketplace
          file: ./abis/FanszoidMarketplace.json
      eventHandlers:
        - event: eventCreated(uint256,address,string)
          handler: handleEventCreated
        - event: AskSetted(uint256,address,uint256)
          handler: handleAskSetted
        - event: AskRemoved(address,uint256)
          handler: handleAskRemoved
        - event: eventEdited(uint256,address,string)
          handler: handleEventEdited
        - event: eventDeleted(uint256,address)
          handler: handleEventDeleted
      file: ./src/handlers/marketplaceHandler.ts