name: Fanszoid CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Code
        uses: actions/checkout@v3
      - name: Setting up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./package.json
      - name: Installing Dependencies
        run: npm install
      - name: Compile Build Data
        run: npm run build-data
      - name: Compile Codegen
        run: npm run codegen
      # - name: Checking Syntax
      #   run: npm run lint:check
      - name: Running Tests and print coverage
        run: graph test
